version: '3.1'
services:
  php:
    image: php:apache
    ports:
      - 80
    volumes:
      - /path/to/php/files:/var/www/html/
    labels:
      - "traefik.enable=true"

      # - "traefik.http.middlewares.apache-https.redirectscheme.scheme=https"

      - 'traefik.http.routers.apachehttp.entrypoints=web'
      - 'traefik.http.routers.apachehttp.rule=Host(`apache.loc`)'
      # - "traefik.http.routers.apachehttp.middlewares=apache-https"

      - "traefik.http.routers.apache.rule=Host(`apache.loc`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls=true"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
    networks:
      - db_network
      - traefik_net

networks:
  traefik_net:
    external: true
  db_network:
    external: true